apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
stringData:
  jwt-secret: "bXNhLXRveS1wcm9qZWN0LXBvcnRmb2xpby10ZXN0LWxvY2FsLWthZmthLXJlZGlzLW1hcmlhZGItc2VjcmV0LWtleS1sZW5ndGgtbG9uZy1lbm91Z2g="
  jwt-refresh-secret: "bXNhLXRveS1wcm9qZWN0LXBvcnRmb2xpby10ZXN0LWt1YmVybmV0ZXMta2Fma2EtcmVkaXMtbWFyaWFkYi1zZWNyZXQta2V5LWxlbmd0aC1sb25nLWVub3VnaA=="

  db-username: "auth_user"
  db-password: "auth1234"
